window.SLOTS_INICIALES = [
  { juego: "Wolf It Up! 3 Reeler", rtp: 94.5 },
  { juego: "Huff N Puff Hard Hat", rtp: 96.0 },
  { juego: "Breaking Bad Mega Fire Blaze", rtp: 95.87 },
  { juego: "Coffee Explosion", rtp: 96.52 },
  { juego: "Piggy Prizes: Railroad Rumble", rtp: 94.12 },
  { juego: "Rumble Riches: Haulin' Gold", rtp: 94.15 },
  { juego: "Piggy Prizes: Wish of Riches 1/2", rtp: 96.05 },
  { juego: "Lemon Juice", rtp: null },
  { juego: "Huff N Puff Haunted Mansion", rtp: 96.0 },
  { juego: "Cash or Nothing", rtp: null },
  { juego: "Sweet Bonanza", rtp: 96.48, casino: "", estado: "", notas: "No disponible en casinos de NJ" },
  { juego: "Almighty Mustang Express", rtp: 94.18 },
  { juego: "Break the Diamond Piggy", rtp: 95.73 },
  { juego: "Double Top Dollar", rtp: null },
  { juego: "Pinball", rtp: null },
  { juego: "Black Diamond Deluxe", rtp: null },
  { juego: "Mystery of the Lamp", rtp: 96.22, notas: "94,00–96,00% según versión" },
].map((s) => ({
  proveedor: "",
  casino: "FanDuel",
  estado: "NJ",
  volatilidad: null,
  hit: null,
  maxWin: null,
  frecuenciaBono: null,
  duracionBono: null,
  spinsBono: null,
  rtpBase: null,
  rtpBono: null,
  fuenteDatos: "",
  fechaDatos: "",
  tipoDatoBono: "",
  version: "",
  revisado: "2026-10-05",
  notas: "",
  ...s,
}));
